#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    queueName: bankMessages
#  #线程池配置
#  task:
#    execution:
#      pool:
#        max-size: 16
#        queue-capacity: 100
#        keep-alive: "10s"
